### ISSUE TITLE
Abandoned ? No releases?

### ISSUE THREAD

**Issue by glagnar** [FIWARE/node-red-contrib-FIWARE_official#8]
Has this been abandoned. It doesn't seem anyone is pushing builds to NPM ? @jason-fox

**Comment by jason-fox** [comment]
It seems that there is no automatic release process attached to the repo. 

I have manually [released](https://github.com/FIWARE/node-red-contrib-FIWARE_official/releases/latest) and [pushed to npm](https://www.npmjs.com/package/node-red-contrib-fiware_official)

This repo is still accepting PRs, but not in active development mode at the moment. This could change in the near future depending upon project funding. If you need me to make another release at some point, just raise a new issue and I can push manually.
